### PR TITLE
Add support for windows platform by MinGW

### PR DESCRIPTION
**Pull request by yqs112358**
Build hdoc as native win32 programs

### CODE REVIEW

**Comment by hdoc** [comment]
Hello. Thank you for your contribution! Also, thank you for adding documentation for your contribution. Both are much appreciated.

There are two minor changes I would like to make to this PR:

- Add a section to the README that indicates Windows isn't officially supported because we (i.e. hdoc, the organization) do not develop or actively work on Windows.
- Remove the unnecessary whitespace changes to the "Repository structure" section of the README.

If you would like, I can make these changes for you.

Lastly, we will need you to sign a Contributor Assignment Agreement (CAA) and email it to [cla@hdoc.io](mailto:cla@hdoc.io) so that this can be merged into our repository. This is unfortunately necessary for legal reasons. I have attached the CAA to this comment.

Thank you!


[hdoc-individual-caa.pdf](https://github.com/hdoc/hdoc/files/8203497/hdoc-individual-caa.pdf)

**Comment by yqs112358** [comment]
OK i have sent this document by e-mail, and added tips about win's support. 
In fact, considering that MinGW is designed for linux projects to be compiled and run on windows **without change any code**, and these GNU toolchains on Windows is quiet active maintained by community, there is no need to worry about the maintain of windows support (it is not need to be maintained manually).

And about those whitespace changes to the "Repository structure", it is strange because i cannot find any difference comparing to the original version - they are just spaces and has not been changed - but git marked them as modified. I think it may be a bug of git and it is just ok to merge.

**Comment by hdoc** [comment]
Thank you for sending the CAA over, we have received it and we will make a few minor changes to this PR next week before merging. Thank you for your contribution!

**Comment by hdoc** [comment]
Hello. Your change has been merged into hdoc with some minor adjustments to the README wording to better match the rest of the project. We have mentioned you by name in the [release notes](https://hdoc.io/release-notes/#version-1-2-2-17-march-2022) as a token of appreciation. Thank you for your contribution!

**Pull request closed without merging**
